[package]
name = "rsrb2"
version = "0.1.0"
authors = ["gm3k4g <thingstuffet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "*"
sdl2-sys = "*"